# Generated by Django 6.0 on 2025-12-29 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stok',
            new_name='stock',
        ),
    ]
